
package caotinging.utils.crm;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICustomerService", targetNamespace = "http://service.caotinging/")
@XmlSeeAlso({
    //ObjectFactory.class
})
public interface ICustomerService {


    /**
     * 
     * @return
     *     returns java.util.List<caotinging.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.caotinging/", className = "caotinging.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.caotinging/", className = "caotinging.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<caotinging.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHasAssociationCustomer", targetNamespace = "http://service.caotinging/", className = "caotinging.service.GetHasAssociationCustomer")
    @ResponseWrapper(localName = "getHasAssociationCustomerResponse", targetNamespace = "http://service.caotinging/", className = "caotinging.service.GetHasAssociationCustomerResponse")
    public List<Customer> getHasAssociationCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns caotinging.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerByTel", targetNamespace = "http://service.caotinging/", className = "caotinging.service.GetCustomerByTel")
    @ResponseWrapper(localName = "getCustomerByTelResponse", targetNamespace = "http://service.caotinging/", className = "caotinging.service.GetCustomerByTelResponse")
    public Customer getCustomerByTel(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDecidedzoneIdByAddress", targetNamespace = "http://service.caotinging/", className = "caotinging.service.GetDecidedzoneIdByAddress")
    @ResponseWrapper(localName = "getDecidedzoneIdByAddressResponse", targetNamespace = "http://service.caotinging/", className = "caotinging.service.GetDecidedzoneIdByAddressResponse")
    public String getDecidedzoneIdByAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assigncustomerstodecidedzone", targetNamespace = "http://service.caotinging/", className = "caotinging.service.Assigncustomerstodecidedzone")
    @ResponseWrapper(localName = "assigncustomerstodecidedzoneResponse", targetNamespace = "http://service.caotinging/", className = "caotinging.service.AssigncustomerstodecidedzoneResponse")
    public Boolean assigncustomerstodecidedzone(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Integer> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<caotinging.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNoAssociationCustomer", targetNamespace = "http://service.caotinging/", className = "caotinging.service.GetNoAssociationCustomer")
    @ResponseWrapper(localName = "getNoAssociationCustomerResponse", targetNamespace = "http://service.caotinging/", className = "caotinging.service.GetNoAssociationCustomerResponse")
    public List<Customer> getNoAssociationCustomer();

}
